spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.try_gpt4_1.common.entity
